<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <IsPackable>false</IsPackable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>Launcher.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.6.4" />
    <PackageReference Include="MSTest.TestFramework" Version="3.6.4" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="launcher">
      <HintPath>..\..\bin\Release\launcher.exe</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Runtime.Serialization" />
  </ItemGroup>
  <Target Name="CopyLauncherExe" AfterTargets="Build">
    <Copy SourceFiles="..\..\bin\Release\launcher.exe" DestinationFolder="$(OutDir)" SkipUnchangedFiles="true" />
  </Target>
</Project>
